slamesher:
  # play ros bag or run it in mobile robot, the configuration used in our real-world demo, the sensor is an ouster OS1-32 lidar
  #read param
  use_sim_time: true
  grt_available: false 
  odom_available: false 
  read_offline_pcd: false
  dataset: 1
  max_steps: 10000
  #register param
  range_max: 60
  range_min: 3.0
  register_times: 5
  cross_overlap: true
  cross_cell_overlap_length: 1
  num_margin_old_cell: 500
  point2mesh: true
  residual_combination: true
  #visualize parameter
  meshing_tsdf: false
  full_cover: true
  visualisation_type: 3
  #gp param
  num_thread: 8
  grid: 1.2
  min_points_num_to_gp: 3
  num_test: 6
  
  variance_register: 0.60
  variance_map_update: 0.50
  variance_map_show: 0.20
  variance_min: 1.36
  variance_sensor: 0.02
  
  test_param:  0


